### ISSUE TITLE
Discourse is throwing 429 for valid requests if running tests continuously

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/tc-services-integration-tests#2]
If you are running tests continuously, Most probably Discourse will start responding with 429 for valid requests, so it may cause failure of tests.

This should be fixed once we get rid of Discourse.

**Comment by gondzo** [comment]
Are you running discourse in docker or using dev environment? if it's docker, rate limiting can be disabled.

**Comment by ThomasKranitsas** [comment]
I tested with the dev instance.

**Comment by vikasrohit** [comment]
We can close this @ThomasKranitsas as ideally the integration tests should be tested again local discourse when testing on local machine.

**Comment by ThomasKranitsas** [comment]
Ok, closing this...
